language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: Opsl2dwJiaSAz6Ys2MFoP/pipdabp1WGNgGOuF0xuuzNLHUBWE6BFXJPKIE40qfSqOOjyWWooXn4Pj/6yMpmJn3o1ywKTvBRex5RdCCkOtmal6YmpKB1t41R8zMYqRrHupKvZWgbTM4OaXSoBq205ov2ChSvlhL8bv9c02pbOVQ=
  - secure: epi748ryQFhLW8woW0U8zYCng3sFSP61JSXqsHr/JZ90sZEhPQcc8H7C5tx1uvBAvTai0JnXgjaU7ai4kRfdbPoodhIF1sY97GW7HYdXUoZeTpxU1y8EyGX7YhmuZcNZlckQyyOn9jHr4qHi7NYiRQh8VqbMJxR/gQARpJBA1o4=
  - secure: TPnUJQmRV6YAwccdMQDMMawRYFJvJW35xIQsAXybqPkaO+b7idIS5YqF5jHWJ+YhwSoeKMg35i5dsqlP4Co2SzhxiyR2geAoublAttl6ODpVFJUuT8CdPdck8Yi5ZCpLXTsl/0ql0lNTav6z1FQ9od1F5mvC4QPiw/dcFI//eMc=
  - secure: tZj87LHyeRXJCf00Pn6ayRXQhDd0B+b2ZecZqA/ZNXqenuPVw1ztVqmujKfU1OWIOUxmKHHW9sNuxdPDDwZ3rwe9SXu9VNZ28bCIv9Oqdo/lfA+cSz6RH5tsy4yrJSAt4dVyJgqu19aAMiBoOjSj6s0vQud3smAl/EZVuBzNxEA=
